=== devgateway/amp/amp/doc/xmlpatcher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- *******************************************************-->
<!-- AID MANAGEMENT PLATFORM								-->
<!-- PATCHER 2 SCHEMA DEFINITION							-->
<!-- (c) 2009 Development Gateway Foundation				-->
<!-- author Mihai Postelnicu - mpostelnicu@dgfoundation.org	-->
<!-- *******************************************************-->

<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher"
	targetNamespace="http://docs.ampdev.net/schemas/xmlpatcher">
	<element name="patch" type="tns:patch"/>


	<complexType name="patch">
		<sequence>
			<element name="jira" type="string" minOccurs="0"
				maxOccurs="1">
				<annotation>
					<documentation>
						Specify here the JIRA ticket that this patch is
						related with. For multiple tickets, use several
						jira elements
					</documentation>
				</annotation>
			</element>
			<element name="keyword" type="string" minOccurs="0"
				maxOccurs="unbounded">
				<annotation>
					<documentation>
						Specify a keyword that relates with this patch.
						This can either be a module name, or keywords
						related to what this patch is addressing
					</documentation>
				</annotation>
			</element>
			<element name="author" type="string" minOccurs="1"
				maxOccurs="unbounded">
				<annotation>
					<documentation>
						Use your SVN user name or your full name. This
						can help track the patch creator in the patcher
						web interface
					</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0"
				maxOccurs="1">
				<annotation>
					<documentation>
						Enter as much info as possible about what
						exactly this patch is addressing. Try to specify
						even obvious stuff, later those obvious things
						become un-obvious and its much harder to
						understand what a patch is supposed to do and
						maybe fix it.
					</documentation>
				</annotation>
			</element>
			<element name="deprecate" type="string" minOccurs="0"
				maxOccurs="unbounded">
				<annotation>
					<documentation>
						The patch name that this patch is deprecating,
						if any. The system first reads all deprecated
						patches (all deprecate entities from all patch
						files) and will never attempt to apply any of
						them. Use multiple deprecate entities if your
						patch is deprecating multiple previous patches.
						For the patch name, you can either include the
						.xml extension of the file name or not.
						Deprecating a patch by another patch (the
						deprecator) means the deprecator will inherit
						its dependencies (if there are any patches that
						depend on a deprecated patch, they will depend
						on the deprecator).
					</documentation>
				</annotation>
			</element>
			<element name="trigger" type="tns:trigger" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="apply" type="tns:scriptGroup" minOccurs="1"
				maxOccurs="1">
				<annotation>
					<documentation>
						The functional part of the patch goes here.
						Write the scripts you want this patch to apply
						to the database. All scripts inside one apply
						element will be attempted to run into a single
						transaction. The transaction is rolledback if it
						fails using the JDBC rollback capabilities. The
						rollback feature is not applicable if you
						manually force commits or if you use DDL
						statements (modify tables/columns/etc). In such
						case you need to use the rollback entity and
						make table backups. If you need several
						transactions use several apply elements.
					</documentation>
				</annotation>
			</element>
			<element name="rollback" type="tns:rollback"
				minOccurs="0" maxOccurs="1">
                <annotation>
                	<documentation>Use this section whenever you need to make sure that by failing, your path will produce data loss.
                	 Candidates are DDL patches, that cannot use the JDBC rollback feature and which if fail they produce unrecoverable loss. 
                	 For such cases use the rollback entity to prepare DDL copies that may be applied if the patch fails. </documentation>
                </annotation>
			</element>
		</sequence>
		<attribute name="retryOnFail" type="boolean" default="false" use="optional">
			<annotation>
				<documentation>
					If true, the failure to run a patch will not disable
					that patch, the system will attempt to re-apply it
					next time.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="closeOnSuccess" type="boolean" use="optional" default="true">
			<annotation>
				<documentation>Defaults to true. If false, this patch will be re-applied even if it succeeded. This is needed in order to produce "cleanup" patches. In such case, the trigger will kick in
whenever some re-occurring garbage data has been found using condition entities, and that requires immediate correction</documentation>
			</annotation></attribute>
		<attribute name="failOnError" type="boolean" default="true">
			<annotation>
				<documentation>Should the migration fail if an error occurs while executing this patch?</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="trigger">
		<annotation>
			<documentation>
				A trigger entity is a set of conditions grouped by any
				(OR) or all (AND) operators. There can be only one
				trigger per patch, if any, and this trigger can hold an
				arbitrary number of conditions (more than 1). The
				trigger of type ALL will return true if all the
				underlying conditions are true, a trigger of type webANY
				will return true if at least one condition is met. A
				trigger's result may be inverted using inverted
				attribute, so a false trigger becomes true.
			</documentation>
		</annotation>
		<sequence>
			<element name="condition" type="tns:condition" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="type" type="tns:triggerType" default="all">
			<annotation>
				<documentation>
					use any if this trigger needs to have at least one
					valid condition, or all if this trigger has to match
					all its conditions
				</documentation>
			</annotation>
		</attribute>
		<attribute name="inverted" type="boolean" default="false">
			<annotation>
				<documentation>
					defaults to false. When true, the trigger is
					inverted (allowed becomes unallowed and vice-versa)
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<simpleType name="triggerType">
		<restriction base="string">
			<enumeration value="all" >
				<annotation>
					<documentation></documentation>
				</annotation></enumeration>
			<enumeration value="any" />
		</restriction>
	</simpleType>

	<complexType name="condition" mixed="true">
		<sequence>
			<element name="param" type="tns:conditionParam" minOccurs="0" maxOccurs="unbounded"/>
			<element name="script" type="tns:script" minOccurs="0" maxOccurs="unbounded"/>
			<element name="test" minOccurs="0" maxOccurs="1" type="string"/>
		</sequence>
		<attribute name="type" type="tns:conditionType"
			default="custom">
		</attribute>
		<attribute name="inverted" type="boolean" default="false"></attribute>
	</complexType>

	<simpleType name="conditionType">
		<restriction base="string">
			<enumeration value="custom">
				<annotation>
					<documentation>The most generic condition type, to which all the
						rest transform to.
						It provides definition space for a series of variables defined using
						script entities plus
						a test. The test entity is a BSH expression that can make use of
						the previously defined variables     				
    				</documentation>
				</annotation>
			</enumeration>
			<enumeration value="dbName">
				<annotation>
					<documentation>This condition type tests if the current schema
						(database) name equals the specify value. This condition works for
						any type of database in AMP as it has specific callers
						to identify the current schema based on which database is currently
						used.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="appliedPatch">
				<annotation>
					<documentation>This condition tests if the specified patch file
						name has already been applied.
						Bear in mind the patcher will try to re-apply all non-applied patches
						until either all patches are applied or no patch has been applied
						in the previous call due to restrictions</documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>

	<complexType name="conditionParam">
	<annotation>
	<documentation>This entity is still under development. Please ignore for the moment...</documentation>
	</annotation>
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="script">
		<sequence>
			<element name="lang" type="tns:lang" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="returnVar" type="string"></attribute>
	</complexType>

	<complexType name="lang">
		<simpleContent>
			<extension base="string">
				<attribute name="type" type="tns:langType"></attribute>
				<attribute name="delimiter" type="string" default=";"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<simpleType name="langType">
		<restriction base="string">
			<enumeration value="sql"></enumeration>
			<enumeration value="hql"></enumeration>
			<enumeration value="mysql"></enumeration>
			<enumeration value="oracle"></enumeration>
			<enumeration value="postgres"></enumeration>
			<enumeration value="bsh"></enumeration>
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>


	<complexType name="scriptGroup">
    	<sequence>
    		<element name="script" type="tns:script" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="rollback">
    	<sequence>
    		<element name="prepare" type="tns:scriptGroup" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="apply" type="tns:scriptGroup" maxOccurs="1" minOccurs="1"></element>
    		<element name="cleanup" type="tns:scriptGroup" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== devgateway/amp/amp/xmlpatches/2.z12.02/AMP-22997-fix-Donor-Report-Generator-menu-visibility.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true"
    xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
    <jira>AMP-22997</jira>
    <keyword>Menu</keyword>
    <author>nmandrescu</author>
    <description>Fix duplicate 'Donor Profile Report' FM entries and re-apply 'Donor Report Generator' menu visibility, since was manually skipped in some countries</description>
    <apply>
        <script>
            <lang delimiter=";" type="postgres">
                <!--  NOTE: this menu management was planned to be done through Menu Admin page -->
                
                <!-- 1.      CLEANUP duplicate 'Donor Profile Report' FM -->
                <!-- change everything to be linked to the latest 'Donor Profile Report' id -->
                UPDATE amp_modules_templates
                    SET module = (SELECT max(id) FROM amp_modules_visibility WHERE name = 'Donor Profile Report')
                    WHERE module IN (SELECT id FROM amp_modules_visibility WHERE name = 'Donor Profile Report');
                <!-- delete older entries -->
                DELETE FROM amp_modules_visibility 
                    WHERE name = 'Donor Profile Report' 
                    AND id != (SELECT max(id) FROM amp_modules_visibility WHERE name = 'Donor Profile Report');
                    
                <!-- 2.      UPDATE menu visibility rule to the single 'Donor Profile Report' entry present -->
                <!-- delete first the previous rule defined (some where manually removed from original patch) to ensure that the correct one applies anew -->
                DELETE FROM amp_visibility_rule_amp_modules_visibility 
                    WHERE rule_id IN (SELECT rule_id FROM amp_menu_entry_view WHERE menu_id = (SELECT id FROM amp_menu_entry WHERE name = 'Donor Report Generator'));
                
                DELETE FROM amp_visibility_rule WHERE id = (
                    SELECT rule_id FROM amp_menu_entry_view WHERE menu_id = (SELECT id FROM amp_menu_entry WHERE name = 'Donor Report Generator'));
                    
                <!-- re-apply menu visibility rule for 'Donor Report Generator' -->
                INSERT INTO amp_visibility_rule(SELECT nextval('amp_visibility_rule_seq'), null, 1);
                UPDATE amp_menu_entry_view SET rule_id=(SELECT currval('amp_visibility_rule_seq')) WHERE menu_id= (SELECT id FROM amp_menu_entry WHERE name = 'Donor Report Generator');
                INSERT INTO amp_visibility_rule_amp_modules_visibility(SELECT currval('amp_visibility_rule_seq'), 
                    (SELECT id FROM amp_modules_visibility WHERE name = 'Donor Profile Report' 
                    AND parent IN (SELECT id FROM amp_modules_visibility WHERE name = 'REPORTING')));
                
            </lang>
        </script>
    </apply>
</tns:patch>

=== devgateway/amp/amp/src/main/resources/xmlpatches/2.7.00/AMP-16001.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true"
	xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../../schemas/xmlpatcher.xsd ">
	<jira>AMP-16001</jira>
	<keyword>pledges</keyword>
	<author>Alex Gartner</author>
	<description>Adding pledges column to donor reports</description>
	<apply>
		<script>
			<lang delimiter=";" type="postgres">
				INSERT INTO amp_columns (columnId,columnName,aliasName,cellType,extractorView) VALUES 
		(nextval('amp_columns_seq'),'Activity Pledges Title','activity_pledges','org.dgfoundation.amp.ar.cell.TrnTextCell','v_activity_pledges_title');
		
			INSERT INTO amp_columns_order (id, columnname, indexorder) VALUES (nextval('amp_columns_order_seq'), 'Activity Pledges', (SELECT max(indexOrder) + 1 FROM amp_columns_order) );
			</lang>
		</script>
	</apply>
</tns:patch>

=== devgateway/amp/amp/xmlpatches/2.2.00/AMP-12493_add_report_categories.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true" xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
    <jira>AMP-12493</jira>
    <keyword>reports</keyword>
    <keyword>category manager</keyword>
    <author>Dare</author>
    <description>Adding category for reports</description>
    
    <trigger type="all">
	      <condition  type="entryInTableMissing" tablename="amp_category_class" columnname="keyName" columnvalue="report_category" />
	</trigger>
       <apply>
        <script>
            <lang  delimiter=";" type="postgres">

	INSERT INTO amp_category_class(id, category_name,is_multiselect,is_ordered, keyName) 
	VALUES((select max(id)+1 from amp_category_class), 'Report Categories', false, false, 'report_category');

	insert into amp_category_value (id, category_value, amp_category_class_id, index_column) 
	select (select max(id)+1 from amp_category_value) as id2, 'On budget', id, '0' 
		from amp_category_class where keyname='report_category';

	insert into amp_category_value (id, category_value, amp_category_class_id, index_column) 
	select (select max(id)+1 from amp_category_value) as id2, 'Off budget', id, '1' 
	from amp_category_class where keyname='report_category';

            </lang>
        </script>
    </apply>
</tns:patch>

=== devgateway/amp/amp/src/main/resources/xmlpatches/2.7.00/AMP-15844-delete-ssc-columns-and-view-for-title-description.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true"
	xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
	<jira>AMP-15844</jira>
	<keyword>Views</keyword>
	<author>Dolghier Constantin</author>
	<description>drop views for fields that are removed: component title and description</description>
	<apply>
		<script>
			<lang delimiter=";" type="postgres">
			
				DELETE FROM amp_report_column WHERE amp_report_id IN (
					SELECT DISTINCT(amp_report_id) FROM amp_report_column where columnid IN (
						SELECT columnid FROM amp_columns WHERE extractorview IN ('v_ssc_component_title', 'v_ssc_component_description')
					)
				);

				DELETE FROM amp_member_reports amr WHERE amr.amp_report_id IN
					(SELECT DISTINCT(amp_report_id) FROM amp_reports ar WHERE  
				(
					SELECT count(*) FROM amp_report_column rc WHERE rc.amp_report_id = ar.amp_report_id) = 0
				);

				DELETE FROM amp_report_log amr WHERE amr.amp_report_id IN
					(SELECT DISTINCT(amp_report_id) FROM amp_reports ar WHERE  
				(
					SELECT count(*) FROM amp_report_column rc WHERE rc.amp_report_id = ar.amp_report_id) = 0
				);

				DELETE FROM amp_team_reports amr WHERE amr.report IN
					(SELECT DISTINCT(amp_report_id) FROM amp_reports ar WHERE  
				(
					SELECT count(*) FROM amp_report_column rc WHERE rc.amp_report_id = ar.amp_report_id) = 0
				);

				DELETE FROM amp_report_measures amr WHERE amr.amp_report_id IN
					(SELECT DISTINCT(amp_report_id) FROM amp_reports ar WHERE  
				(
					SELECT count(*) FROM amp_report_column rc WHERE rc.amp_report_id = ar.amp_report_id) = 0
				);
				
				DELETE FROM amp_filter_data ar WHERE (SELECT count(*) FROM amp_report_column rc WHERE rc.amp_report_id = ar.amp_report_id) = 0;
				DELETE from amp_report_hierarchy arh WHERE NOT EXISTS (select * from amp_report_column arc WHERE arc.amp_report_id = arh.amp_report_id AND arc.columnid = arh.columnid);
				
				DELETE FROM amp_reports ar WHERE (
					SELECT count(*) FROM amp_report_column rc WHERE rc.amp_report_id = ar.amp_report_id) = 0;

                drop view if exists v_ssc_component_title;
                drop view if exists v_ssc_component_description;
			</lang>
		</script>
	</apply>
</tns:patch>

=== devgateway/amp/amp/xmlpatches/general/views/v_mondrian_locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="false" retryOnFail="true"
	xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
	<jira>AMP-17836</jira>
	<keyword>Views</keyword>
	<author>Constantin Dolghier</author>
	<description>recreate view, this will always be the last version of the view</description>
	<trigger type="all">
		<condition type="custom">
			<script returnVar="val">
				<lang type="sql">
					SELECT settingsvalue FROM amp_global_settings where settingsname='Recreate the views on the next server restart';
				</lang>
			</script>
 			<test>val.equalsIgnoreCase("true")</test>
		</condition>
	</trigger> 
	<apply>
		<script>
			<lang delimiter=";" type="postgres">
				DROP VIEW IF EXISTS v_mondrian_locations;
			    CREATE OR REPLACE VIEW v_mondrian_locations AS 
					SELECT acvl.id, acvl.parent_location, acvl.location_name, 
						COALESCE(getlocationidbyimplloc(acvl.id, 'Country'), 999999999) AS country_id, COALESCE(getlocationname(getlocationidbyimplloc(acvl.id, 'Country')), 'Undefined') AS country_name,
						COALESCE(getlocationidbyimplloc(acvl.id, 'Region'), 999999999) AS region_id, COALESCE(getlocationname(getlocationidbyimplloc(acvl.id, 'Region')), 'Undefined') AS region_name,
						COALESCE(getlocationidbyimplloc(acvl.id, 'Zone'), 999999999) AS zone_id, COALESCE(getlocationname(getlocationidbyimplloc(acvl.id, 'Zone')), 'Undefined') AS zone_name,
						COALESCE(getlocationidbyimplloc(acvl.id, 'District'), 999999999) AS district_id, COALESCE(getlocationname(getlocationidbyimplloc(acvl.id, 'District')), 'Undefined') AS district_name

						FROM amp_category_value_location acvl
						
					UNION ALL
						
					SELECT 999999999, null, 'Undefined', 999999999, 'Undefined', 999999999, 'Undefined', 999999999, 'Undefined', 999999999, 'Undefined';
			</lang>
		</script>
	</apply>
</tns:patch>

=== devgateway/amp/amp/xmlpatches/general/views/v_agreement_title_code.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="false" retryOnFail="true"
	xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
	<jira>AMP-13984</jira>
	<keyword>Views</keyword>
	<keyword>Agreement</keyword>
	<author>Alex</author>
	<description>Views for agreement ( title + code )</description>
	<trigger type="all">
		<condition type="custom">
			<script returnVar="val">
				<lang type="sql">
					SELECT settingsvalue FROM amp_global_settings where settingsname='Recreate the views on the next server restart';
				</lang>
			</script>
 			<test>val.equalsIgnoreCase("true")</test>
		</condition>
	</trigger> 
	<apply>
		<script>
			<lang delimiter=";" type="postgres">
					DROP VIEW IF EXISTS v_agreement_title_code;
			    	CREATE OR REPLACE VIEW v_agreement_title_code AS 
			    	SELECT DISTINCT f.amp_activity_id, ag.title || ' - ' || ag.code as "Agreement Title + Code", ag.id, ag.code AS "Agreement Code", o.name AS "Donor Agency", o.amp_org_id, ag.title as agreement_title 
			    	FROM amp_agreement ag, amp_funding f, amp_organisation o 
  					WHERE f.agreement = ag.id AND f.amp_donor_org_id = o.amp_org_id;
        		</lang>
		</script>
	</apply>
</tns:patch>

=== devgateway/amp/amp/xmlpatches/2.z10.21/AMP-19800_MAX_LOCATIONS_ICONS.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="false"
        xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
        <jira>AMP-19800</jira>
        <keyword>Global settings</keyword>
        <author>mihai</author>
        <description>Add the ability to configure the number of locations to show icons on the Project Sites map</description>
        <apply>
                <script>
                        <lang delimiter=";" type="postgres">
                                INSERT INTO amp_global_settings (id, settingsname, settingsvalue, possiblevalues, description, section)
                                VALUES (nextval('amp_global_settings_seq'), 'Show icons for Project Sites for locations up to', '0', 't_Integer', 'If 0 then it will show colored points, otherwise it will set the upper limit (for the number of locations) to show icons (if lower) or points (if higher).', 'general');
                        </lang>
                </script>
        </apply>
</tns:patch>

=== devgateway/amp/amp/src/main/resources/xmlpatches/3.2.02/AMP-28511-component-funding-proc.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true"
	xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
	<jira>AMP-28511</jira>
	<keyword>Views</keyword>
	<author>vchihai</author>
	<description>update component funding proc for ETL</description>
	<apply>
		<script>
			<lang delimiter="@" type="postgres"><![CDATA[

				CREATE OR REPLACE FUNCTION component_funding_modified_proc() RETURNS trigger AS $BODY$
				    BEGIN
						IF (NEW.amp_component_id IS NOT NULL) THEN
				        	INSERT INTO amp_etl_changelog(entity_name, entity_id) VALUES ('component', NEW.amp_component_id);

				        	INSERT INTO amp_etl_changelog(entity_name, entity_id)
				        		SELECT 'activity', ac.amp_activity_id
				        		FROM amp_component_funding aaf
				        		JOIN amp_components ac
				        		ON ac.amp_component_id = aaf.amp_component_id
				        		AND aaf.amp_component_id = NEW.amp_component_id;
				        END IF;
						RETURN NEW;
					END;
				$BODY$ LANGUAGE plpgsql@@@

				CREATE OR REPLACE FUNCTION component_funding_deleted_proc() RETURNS trigger AS $BODY$
				    BEGIN
				    	IF (OLD.amp_component_id IS NOT NULL) THEN
				        	INSERT INTO amp_etl_changelog(entity_name, entity_id) VALUES ('component', OLD.amp_component_id);

				        	INSERT INTO amp_etl_changelog(entity_name, entity_id)
				        		SELECT 'activity', aac.amp_activity_id
				        		FROM amp_component_funding aaf
				        		JOIN amp_components ac
				        		ON ac.amp_component_id = aaf.amp_component_id
				        		AND aaf.amp_component_id = OLD.amp_component_id;
				        END IF;
				        RETURN OLD;
				    END;
				$BODY$ LANGUAGE plpgsql@@@
    
			]]></lang>
		</script>
	</apply>
</tns:patch>
