=== devgateway/amp/amp/doc/xmlpatcher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- *******************************************************-->
<!-- AID MANAGEMENT PLATFORM								-->
<!-- PATCHER 2 SCHEMA DEFINITION							-->
<!-- (c) 2009 Development Gateway Foundation				-->
<!-- author Mihai Postelnicu - mpostelnicu@dgfoundation.org	-->
<!-- *******************************************************-->

<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher"
	targetNamespace="http://docs.ampdev.net/schemas/xmlpatcher">
	<element name="patch" type="tns:patch"/>


	<complexType name="patch">
		<sequence>
			<element name="jira" type="string" minOccurs="0"
				maxOccurs="1">
				<annotation>
					<documentation>
						Specify here the JIRA ticket that this patch is
						related with. For multiple tickets, use several
						jira elements
					</documentation>
				</annotation>
			</element>
			<element name="keyword" type="string" minOccurs="0"
				maxOccurs="unbounded">
				<annotation>
					<documentation>
						Specify a keyword that relates with this patch.
						This can either be a module name, or keywords
						related to what this patch is addressing
					</documentation>
				</annotation>
			</element>
			<element name="author" type="string" minOccurs="1"
				maxOccurs="unbounded">
				<annotation>
					<documentation>
						Use your SVN user name or your full name. This
						can help track the patch creator in the patcher
						web interface
					</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0"
				maxOccurs="1">
				<annotation>
					<documentation>
						Enter as much info as possible about what
						exactly this patch is addressing. Try to specify
						even obvious stuff, later those obvious things
						become un-obvious and its much harder to
						understand what a patch is supposed to do and
						maybe fix it.
					</documentation>
				</annotation>
			</element>
			<element name="deprecate" type="string" minOccurs="0"
				maxOccurs="unbounded">
				<annotation>
					<documentation>
						The patch name that this patch is deprecating,
						if any. The system first reads all deprecated
						patches (all deprecate entities from all patch
						files) and will never attempt to apply any of
						them. Use multiple deprecate entities if your
						patch is deprecating multiple previous patches.
						For the patch name, you can either include the
						.xml extension of the file name or not.
						Deprecating a patch by another patch (the
						deprecator) means the deprecator will inherit
						its dependencies (if there are any patches that
						depend on a deprecated patch, they will depend
						on the deprecator).
					</documentation>
				</annotation>
			</element>
			<element name="trigger" type="tns:trigger" minOccurs="0"
				maxOccurs="1">
			</element>
			<element name="apply" type="tns:scriptGroup" minOccurs="1"
				maxOccurs="1">
				<annotation>
					<documentation>
						The functional part of the patch goes here.
						Write the scripts you want this patch to apply
						to the database. All scripts inside one apply
						element will be attempted to run into a single
						transaction. The transaction is rolledback if it
						fails using the JDBC rollback capabilities. The
						rollback feature is not applicable if you
						manually force commits or if you use DDL
						statements (modify tables/columns/etc). In such
						case you need to use the rollback entity and
						make table backups. If you need several
						transactions use several apply elements.
					</documentation>
				</annotation>
			</element>
			<element name="rollback" type="tns:rollback"
				minOccurs="0" maxOccurs="1">
                <annotation>
                	<documentation>Use this section whenever you need to make sure that by failing, your path will produce data loss.
                	 Candidates are DDL patches, that cannot use the JDBC rollback feature and which if fail they produce unrecoverable loss. 
                	 For such cases use the rollback entity to prepare DDL copies that may be applied if the patch fails. </documentation>
                </annotation>
			</element>
		</sequence>
		<attribute name="retryOnFail" type="boolean" default="false" use="optional">
			<annotation>
				<documentation>
					If true, the failure to run a patch will not disable
					that patch, the system will attempt to re-apply it
					next time.
				</documentation>
			</annotation>
		</attribute>
		<attribute name="closeOnSuccess" type="boolean" use="optional" default="true">
			<annotation>
				<documentation>Defaults to true. If false, this patch will be re-applied even if it succeeded. This is needed in order to produce "cleanup" patches. In such case, the trigger will kick in
whenever some re-occurring garbage data has been found using condition entities, and that requires immediate correction</documentation>
			</annotation></attribute>
		<attribute name="failOnError" type="boolean" default="true">
			<annotation>
				<documentation>Should the migration fail if an error occurs while executing this patch?</documentation>
			</annotation>
		</attribute>
	</complexType>

	<complexType name="trigger">
		<annotation>
			<documentation>
				A trigger entity is a set of conditions grouped by any
				(OR) or all (AND) operators. There can be only one
				trigger per patch, if any, and this trigger can hold an
				arbitrary number of conditions (more than 1). The
				trigger of type ALL will return true if all the
				underlying conditions are true, a trigger of type webANY
				will return true if at least one condition is met. A
				trigger's result may be inverted using inverted
				attribute, so a false trigger becomes true.
			</documentation>
		</annotation>
		<sequence>
			<element name="condition" type="tns:condition" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="type" type="tns:triggerType" default="all">
			<annotation>
				<documentation>
					use any if this trigger needs to have at least one
					valid condition, or all if this trigger has to match
					all its conditions
				</documentation>
			</annotation>
		</attribute>
		<attribute name="inverted" type="boolean" default="false">
			<annotation>
				<documentation>
					defaults to false. When true, the trigger is
					inverted (allowed becomes unallowed and vice-versa)
				</documentation>
			</annotation>
		</attribute>
	</complexType>

	<simpleType name="triggerType">
		<restriction base="string">
			<enumeration value="all" >
				<annotation>
					<documentation></documentation>
				</annotation></enumeration>
			<enumeration value="any" />
		</restriction>
	</simpleType>

	<complexType name="condition" mixed="true">
		<sequence>
			<element name="param" type="tns:conditionParam" minOccurs="0" maxOccurs="unbounded"/>
			<element name="script" type="tns:script" minOccurs="0" maxOccurs="unbounded"/>
			<element name="test" minOccurs="0" maxOccurs="1" type="string"/>
		</sequence>
		<attribute name="type" type="tns:conditionType"
			default="custom">
		</attribute>
		<attribute name="inverted" type="boolean" default="false"></attribute>
	</complexType>

	<simpleType name="conditionType">
		<restriction base="string">
			<enumeration value="custom">
				<annotation>
					<documentation>The most generic condition type, to which all the
						rest transform to.
						It provides definition space for a series of variables defined using
						script entities plus
						a test. The test entity is a BSH expression that can make use of
						the previously defined variables     				
    				</documentation>
				</annotation>
			</enumeration>
			<enumeration value="dbName">
				<annotation>
					<documentation>This condition type tests if the current schema
						(database) name equals the specify value. This condition works for
						any type of database in AMP as it has specific callers
						to identify the current schema based on which database is currently
						used.</documentation>
				</annotation>
			</enumeration>
			<enumeration value="appliedPatch">
				<annotation>
					<documentation>This condition tests if the specified patch file
						name has already been applied.
						Bear in mind the patcher will try to re-apply all non-applied patches
						until either all patches are applied or no patch has been applied
						in the previous call due to restrictions</documentation>
				</annotation>
			</enumeration>
		</restriction>
	</simpleType>

	<complexType name="conditionParam">
	<annotation>
	<documentation>This entity is still under development. Please ignore for the moment...</documentation>
	</annotation>
		<simpleContent>
			<extension base="string">
				<attribute name="name" type="string"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<complexType name="script">
		<sequence>
			<element name="lang" type="tns:lang" minOccurs="1" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="returnVar" type="string"></attribute>
	</complexType>

	<complexType name="lang">
		<simpleContent>
			<extension base="string">
				<attribute name="type" type="tns:langType"></attribute>
				<attribute name="delimiter" type="string" default=";"></attribute>
			</extension>
		</simpleContent>
	</complexType>

	<simpleType name="langType">
		<restriction base="string">
			<enumeration value="sql"></enumeration>
			<enumeration value="hql"></enumeration>
			<enumeration value="mysql"></enumeration>
			<enumeration value="oracle"></enumeration>
			<enumeration value="postgres"></enumeration>
			<enumeration value="bsh"></enumeration>
			<whiteSpace value="collapse"></whiteSpace>
		</restriction>
	</simpleType>


	<complexType name="scriptGroup">
    	<sequence>
    		<element name="script" type="tns:script" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="rollback">
    	<sequence>
    		<element name="prepare" type="tns:scriptGroup" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="apply" type="tns:scriptGroup" maxOccurs="1" minOccurs="1"></element>
    		<element name="cleanup" type="tns:scriptGroup" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
</schema>

=== devgateway/amp/amp/src/main/resources/xmlpatches/2.z12.06/AMP-25177-rename-mtef-columns-regexp.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true" xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
    <jira>AMP-25177</jira>
    <keyword>MTEF column name</keyword>
    <author>vchihai</author>
    <description>Rename MTEF column names with regexp</description>
    <apply>
        <script>
            <lang delimiter=";" type="postgres">


				UPDATE amp_columns SET aliasname = 'mtef' || (substring (columnname, '\d\d\d\d$')),
				tokenexpression = columnname,
				extractorview='v_mtef_funding',
				celltype = 'org.dgfoundation.amp.ar.cell.ComputedAmountCell'
				WHERE columnname ~'^MTEF \d\d\d\d$'
				AND aliasname is null
				AND tokenexpression is null
				AND extractorview = 'v_empty_text_column'
				AND celltype = 'org.dgfoundation.amp.ar.cell.TextCell';

            	DELETE FROM amp_columns 
            	WHERE columnname ~ '^(MTEF|Real MTEF|Projection MTEF Projections|Pipeline MTEF Projections) \d\d\d\d$' AND tokenexpression is null;
            	
            	UPDATE amp_columns 
            	SET columnname = regexp_replace(columnname, '[\/]\d\d\d\d$', ''), tokenexpression = regexp_replace(tokenexpression, '[\/]\d\d\d\d$', '') 
            	WHERE columnname ~ '^(MTEF|Real MTEF|Projection MTEF Projections|Pipeline MTEF Projections) \d\d\d\d[\/]\d\d\d\d$';
            	
            	UPDATE amp_columns 
            	SET tokenexpression = regexp_replace(tokenexpression, 'Real ', '') 
            	WHERE tokenexpression ~ '^(Real Projection MTEF Projections|Real Pipeline MTEF Projections) \d\d\d\d$';
            	
            	UPDATE amp_fields_visibility 
            	SET name = regexp_replace(name, '[\/]\d\d\d\d$', ''), description = regexp_replace(description, '[\/]\d\d\d\d$', '') 
            	WHERE name ~ '^(MTEF|Real MTEF|Projection MTEF Projections|Pipeline MTEF Projections) \d\d\d\d[\/]\d\d\d\d$';
            	
            	UPDATE amp_fields_visibility 
            	SET description = regexp_replace(name, 'Real ', '')
            	WHERE description ~ '^(Real Projection MTEF Projections|Real Pipeline MTEF Projections) \d\d\d\d$';
            </lang>
        </script>
    </apply>
</tns:patch>

=== devgateway/amp/amp/src/main/resources/xmlpatches/2.z10.32/AMP-20045.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true" xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
    <jira>AMP-20045</jira>
    <keyword>Hide Add New Document / Add New WebLink / Add document from repository if section is disabled</keyword>
    <author>vlimansky</author>
    <description>Clean up old visibility items</description>
    <apply>
        <script>
            <lang delimiter=";" type="postgres">
                delete from amp_modules_templates where ampModule in (select id from amp_modules_visibility where name like '%/Activity Form/Related Documents/Add New WebLink Link%');
                delete from amp_modules_visibility where name like '%/Activity Form/Related Documents/Add New WebLink Link%';

                delete from amp_modules_templates where ampModule in (select id from amp_modules_visibility where name like '%/Activity Form/Related Documents/Add New Document Link%');
                delete from amp_modules_visibility where name like '%/Activity Form/Related Documents/Add New Document Link%';

            </lang>
        </script>
    </apply>
</tns:patch>

=== devgateway/amp/amp/xmlpatches/3.5.00/AMP-29855-locs-merge-fixing.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true"
           xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../../doc/xmlpatcher.xsd ">
    <jira>AMP-29855</jira>
    <keyword>location views fix</keyword>
    <author>Viorel Chihai</author>
    <description>
        Fix location views after merging
    </description>
    <apply>
        <script>
            <lang delimiter="@@@" type="postgres"><![CDATA[

                DROP VIEW IF EXISTS v_amp_location_cache CASCADE@@@

                CREATE VIEW v_amp_location_cache AS
                SELECT
                  acvl.id AS acvl_id, acvl.location_name AS acvl_name,
                  acvl.parent_location,
                  getlocationidbyimplloc(acvl.id, 'Administrative Level 0'::character varying) AS adm_level_0_id, getlocationname(getlocationidbyimplloc(acvl.id, 'Administrative Level 0'::character varying)) as adm_level_0_name,
                  getlocationidbyimplloc(acvl.id, 'Administrative Level 1'::character varying) AS adm_level_1_id, getlocationname(getlocationidbyimplloc(acvl.id, 'Administrative Level 1'::character varying)) as adm_level_1_name,
                  getlocationidbyimplloc(acvl.id, 'Administrative Level 2'::character varying) AS adm_level_2_id, getlocationname(getlocationidbyimplloc(acvl.id, 'Administrative Level 2'::character varying)) as adm_level_2_name,
                  getlocationidbyimplloc(acvl.id, 'Administrative Level 3'::character varying) AS adm_level_3_id, getlocationname(getlocationidbyimplloc(acvl.id, 'Administrative Level 3'::character varying)) as adm_level_3_name,
                  getlocationidbyimplloc(acvl.id, 'Administrative Level 4'::character varying) AS adm_level_4_id, getlocationname(getlocationidbyimplloc(acvl.id, 'Administrative Level 4'::character varying)) as adm_level_4_name
                FROM amp_category_value_location acvl
                ORDER BY acvl.id@@@

                CREATE VIEW v_ni_all_locations_with_levels AS
					SELECT acvl_id, acvl_name, parent_location, getlocationdepth(acvl_id) AS location_depth,
						COALESCE(adm_level_0_id, - acvl_id) AS adm_level_0_id, COALESCE(adm_level_0_name, 'Undefined') AS adm_level_0_name,
						COALESCE(adm_level_1_id, - acvl_id) AS adm_level_1_id, COALESCE(adm_level_1_name, 'Undefined') AS adm_level_1_name,
						COALESCE(adm_level_2_id, - acvl_id) AS adm_level_2_id, COALESCE(adm_level_2_name, 'Undefined') AS adm_level_2_name,
						COALESCE(adm_level_3_id, - acvl_id) AS adm_level_3_id, COALESCE(adm_level_3_name, 'Undefined') AS adm_level_3_name,
						COALESCE(adm_level_4_id, - acvl_id) AS adm_level_4_id, COALESCE(adm_level_4_name, 'Undefined') AS adm_level_4_name
					FROM v_amp_location_cache@@@

				DROP TABLE IF EXISTS ni_all_locations_with_levels CASCADE@@@
				CREATE TABLE ni_all_locations_with_levels AS
					SELECT * FROM v_ni_all_locations_with_levels@@@

				CREATE INDEX ni_alwl_acvl_id ON ni_all_locations_with_levels(acvl_id)@@@
				CREATE INDEX ni_alwl_parent_id ON ni_all_locations_with_levels(parent_location)@@@
				CREATE INDEX ni_alwl_depth ON ni_all_locations_with_levels(location_depth)@@@
				CREATE INDEX ni_alwl_adm_level_0_id ON ni_all_locations_with_levels(adm_level_0_id)@@@
				CREATE INDEX ni_alwl_adm_level_1_id ON ni_all_locations_with_levels(adm_level_1_id)@@@
				CREATE INDEX ni_alwl_adm_level_2_id ON ni_all_locations_with_levels(adm_level_2_id)@@@
				CREATE INDEX ni_alwl_adm_level_3_id ON ni_all_locations_with_levels(adm_level_3_id)@@@
				CREATE INDEX ni_alwl_adm_level_4_id ON ni_all_locations_with_levels(adm_level_4_id)@@@

                CREATE TRIGGER ni_locations_changed
                    AFTER INSERT OR UPDATE OR DELETE ON ni_all_locations_with_levels
                    FOR EACH STATEMENT
                        EXECUTE PROCEDURE dimension_updated_proc()@@@

                DROP TABLE IF EXISTS ni_all_locations_with_levels CASCADE@@@

				CREATE TABLE ni_all_locations_with_levels AS
					SELECT * FROM v_ni_all_locations_with_levels@@@

					CREATE TRIGGER ni_locations_changed
                    AFTER INSERT OR UPDATE OR DELETE ON ni_all_locations_with_levels
                    FOR EACH STATEMENT
                        EXECUTE PROCEDURE dimension_updated_proc()@@@

                CREATE OR REPLACE FUNCTION update_location_level_caches_internal()
                    RETURNS bigint AS
                    $BODY$
                        BEGIN
                            TRUNCATE ni_all_locations_with_levels;
                            INSERT INTO ni_all_locations_with_levels
                                SELECT * FROM v_ni_all_locations_with_levels;

                            RETURN 1;
                            end;
                        $BODY$
                LANGUAGE plpgsql VOLATILE@@@

                CREATE TEMPORARY TABLE DUMMY_TABLE AS
                SELECT update_location_level_caches_internal() FROM (select 1) AS dual @@@

                DROP TABLE DUMMY_TABLE @@@

                UPDATE amp_global_settings SET settingsvalue = 'true' WHERE settingsname='Recreate the views on the next server restart' @@@
            ]]></lang>
        </script>
    </apply>
</tns:patch>

=== devgateway/amp/amp/src/main/resources/xmlpatches/3.5.00/AMP-29544-recreate-orgs-dimension.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true"
	xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../../doc/xmlpatcher.xsd ">
	<jira>AMP-29544</jira>
	<keyword>organisations</keyword>
	<author>vchihai</author>
	<description>recreate orgs dimension by adding amp_country_id from amp_organisation</description>
	<apply>
		<script>
			<lang delimiter="@" type="postgres">
  				DROP VIEW IF EXISTS v_ni_all_orgs_dimension CASCADE@@@
				CREATE OR REPLACE VIEW v_ni_all_orgs_dimension AS
					SELECT
						org.amp_org_id AS org_id, org.name AS org_name, org.org_code, org.acronym AS org_acronym,
						grp.amp_org_grp_id AS org_grp_id, grp.org_grp_name AS org_grp_name,
						aot.amp_org_type_id AS org_type_id, aot.org_type AS org_type_name, aot.org_type_code,
				        org.budget_org_code, org.amp_country_id as amp_country_id
						FROM amp_organisation org
							FULL OUTER JOIN amp_org_group grp ON org.org_grp_id = grp.amp_org_grp_id
							FULL OUTER JOIN amp_org_type aot ON grp.org_type = aot.amp_org_type_id
							LEFT JOIN amp_category_value_location acv ON org.amp_country_id = acv.id@@@
										
				DROP TABLE IF EXISTS ni_all_orgs_dimension CASCADE@@@
				CREATE TABLE ni_all_orgs_dimension AS SELECT * FROM v_ni_all_orgs_dimension@@@ <!-- will be overridden ASAP, we don't want nulls -->
				
				CREATE INDEX aod_org_id ON ni_all_orgs_dimension(org_id)@@@
				CREATE INDEX aod_org_grp_id ON ni_all_orgs_dimension(org_grp_id)@@@
				CREATE INDEX aod_org_type_id ON ni_all_orgs_dimension(org_type_id)@@@
				CREATE INDEX aod_amp_country_id ON ni_all_orgs_dimension(amp_country_id)@@@

				CREATE OR REPLACE FUNCTION update_organisation_caches_internal()
				RETURNS bigint AS
				$BODY$
				BEGIN
					TRUNCATE ni_all_orgs_dimension;

					CREATE TEMPORARY SEQUENCE ni_all_orgs_dimension_seq;
					INSERT INTO ni_all_orgs_dimension
						SELECT
							COALESCE(org_id, - nextval('ni_all_orgs_dimension_seq')) AS org_id, COALESCE(org_name, '#') AS org_name, COALESCE(org_code, '#') AS org_code, COALESCE(org_acronym, '#') AS org_acronym,
							COALESCE(org_grp_id, - nextval('ni_all_orgs_dimension_seq')) AS org_grp_id, COALESCE(org_grp_name, '#') AS org_grp_name,
							COALESCE(org_type_id, - nextval('ni_all_orgs_dimension_seq')) AS org_type_id, COALESCE(org_type_name,
								'#') AS org_grp_name, COALESCE(org_type_code, '#') AS org_type_code, COALESCE(budget_org_code, '#') AS budget_org_code,
							COALESCE(amp_country_id, - nextval('ni_all_orgs_dimension_seq')) AS amp_country_id
						FROM v_ni_all_orgs_dimension;

					DROP SEQUENCE ni_all_orgs_dimension_seq;
					RETURN 1;
				end;
				$BODY$
				LANGUAGE plpgsql VOLATILE; @@@
				
				CREATE OR REPLACE FUNCTION update_organisation_caches()
  				RETURNS TRIGGER AS
				$BODY$
					declare	dummy bigint;
					BEGIN
						SELECT into dummy update_organisation_caches_internal() FROM (select 1) AS dual;
						RETURN NULL;
					end;
				$BODY$
				LANGUAGE plpgsql VOLATILE; @@@

				DROP TRIGGER IF EXISTS update_organisation_caches_trg_organisation ON amp_organisation@@@
				DROP TRIGGER IF EXISTS update_organisation_caches_trg_org_group ON amp_org_group@@@
				DROP TRIGGER IF EXISTS update_organisation_caches_trg_org_type ON amp_org_type@@@

				CREATE TRIGGER update_organisation_caches_trg_organisation AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON amp_organisation
    				EXECUTE PROCEDURE update_organisation_caches() @@@
    				
				CREATE TRIGGER update_organisation_caches_trg_org_group AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON amp_org_group
    				EXECUTE PROCEDURE update_organisation_caches() @@@
    				
				CREATE TRIGGER update_organisation_caches_trg_org_type AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON amp_org_type
    				EXECUTE PROCEDURE update_organisation_caches() @@@

				CREATE TEMPORARY TABLE DUMMY_TABLE_YOU_SHOULD_NOT_SEE_IT_WE_ARE_TRYING_TO_MAKE_XML_PATCHER_HAPPY_1 AS SELECT update_organisation_caches_internal() FROM (select 1) AS dual @@@
				DROP TABLE DUMMY_TABLE_YOU_SHOULD_NOT_SEE_IT_WE_ARE_TRYING_TO_MAKE_XML_PATCHER_HAPPY_1 @@@
				
				UPDATE amp_global_settings SET settingsvalue = 'true' WHERE settingsname='Recreate the views on the next server restart' @@@	
			</lang>
		</script>
	</apply>
</tns:patch>

=== devgateway/amp/amp/src/main/resources/xmlpatches/2.z13.02/AMP-27713-create-perf-alert-table.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true"
    xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
    <jira>AMP-27713</jira>
    <keyword>activity performance table</keyword>
    <author>vchihai</author>
    <description>create amp activity performance rule table</description>
    <apply>
        <script>
            <lang delimiter=";" type="postgres">
            
                DROP TABLE IF EXISTS amp_activity_performance_rule CASCADE;

                CREATE TABLE public.amp_activity_performance_rule (
					amp_activity_id bigint NOT NULL,
					performance_rule_id bigint NOT NULL,
					CONSTRAINT amp_activity_performance_rule_pkey PRIMARY KEY (amp_activity_id, performance_rule_id)
				);
                
            </lang>
        </script>
    </apply>
</tns:patch>

=== devgateway/amp/amp/src/main/resources/xmlpatches/2.z12.07/AMP-23152-remove-obsolete-messages-v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true"
    xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../doc/xmlpatcher.xsd ">
    <jira>AMP-23152</jira>
    <keyword>translations</keyword>
    <author>vchihai</author>
    <description>Remove obsolete messages</description>
    <apply>
        <script>
            <lang delimiter=";" type="postgres">
				
						DELETE FROM dg_message WHERE message_key IN (
										SELECT message_key from dg_message where message_utf8 IN (
													'First Name is Blank', 'LastName is Blank', 'New password is required', 'New password is required.', 
													'Old password is required', 'Old password is required.'));
            </lang>
        </script>
    </apply>
</tns:patch>

=== devgateway/amp/amp/src/main/resources/xmlpatches/2.7.22/AMP-17395-put-null-in-zero-percentage-entries-from-activity-fields.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true"
           xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../../schemas/xmlpatcher.xsd ">
    <jira>AMP-17395</jira>
    <keyword>Views</keyword>
    <author>Dolghier Constantin</author>
    <description>put NULLs instead of zeroes in the activity-percentages-fields where zero would be illegal</description>
    <apply>
        <script>
            <lang delimiter=";" type="postgres">
				update amp_org_role SET percentage = NULL WHERE percentage = 0;
				update amp_activity_location set location_percentage = NULL where location_percentage = 0;
				update amp_activity_program set program_percentage = NULL where program_percentage = 0;
				update amp_activity_sector set sector_percentage = NULL where sector_percentage = 0;
			</lang>
        </script>
    </apply>
</tns:patch>

=== devgateway/amp/amp/src/main/resources/xmlpatches/2.4.12/AMP-16347.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patch closeOnSuccess="true" retryOnFail="true" xmlns:tns="http://docs.ampdev.net/schemas/xmlpatcher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://docs.ampdev.net/schemas/xmlpatcher ../../schemas/xmlpatcher.xsd ">
	<jira>AMP-16347</jira>
	<keyword>mondrian cache</keyword>
	<author>cdolghier</author>
	<description>restore cached_amp_activity_group</description>
	<apply>
		<script>
			<lang delimiter=";" type="postgres">
				TRUNCATE cached_amp_activity_group;
				INSERT INTO cached_amp_activity_group SELECT * FROM amp_activity_group WHERE amp_activity_last_version_id IS NOT NULL;
			</lang>
		</script>
	</apply>
</tns:patch>
